-- room_entries — 종목 유료방 1회 입장 기록
-- ─────────────────────────────────────────────
-- 구독(pro_members)과 별개. 1회 입장료이므로 만료/자동퇴장 없음.
-- 흐름: pending(신청) → approved(승인·링크발급) | rejected(거절)
-- Supabase SQL Editor에서 1회 실행.

create table if not exists room_entries (
  id                bigint generated by default as identity primary key,
  telegram_id       bigint      not null,
  telegram_username text,                       -- '@name' (대조용)
  telegram_name     text,
  room_id           bigint,                     -- rooms.id
  room_name         text,
  room_chat_id      text,
  status            text        not null default 'pending',  -- pending | approved | rejected
  invite_link       text,
  requested_at      timestamptz not null default now(),
  approved_at       timestamptz,
  approved_by       text
);

create index if not exists idx_room_entries_tid    on room_entries (telegram_id);
create index if not exists idx_room_entries_status on room_entries (status);
create index if not exists idx_room_entries_room   on room_entries (room_id);

-- 같은 사람이 같은 방을 중복 '승인'받지 않도록 (pending/rejected는 중복 허용)
create unique index if not exists uq_room_entries_approved
  on room_entries (telegram_id, room_id)
  where status = 'approved';
