-- ============================================================
--  프로 채널 유료 멤버 관리 테이블
--  실행: Supabase SQL Editor → 실행
-- ============================================================

-- 1) 테이블 생성
CREATE TABLE IF NOT EXISTS pro_members (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id    BIGINT      NOT NULL UNIQUE,          -- 텔레그램 유저 숫자 ID
    telegram_name  TEXT        DEFAULT '',                -- @username
    real_name      TEXT        DEFAULT '',                -- 실명 / 닉네임
    paid_until     DATE        NOT NULL,                  -- 구독 만료일
    is_active      BOOLEAN     NOT NULL DEFAULT TRUE,     -- 활성 구독 여부
    in_channel     BOOLEAN     NOT NULL DEFAULT FALSE,    -- 현재 채널 내 여부
    memo           TEXT        DEFAULT '',                -- 관리 메모
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2) 인덱스
CREATE INDEX IF NOT EXISTS idx_pro_members_paid_until ON pro_members (paid_until);
CREATE INDEX IF NOT EXISTS idx_pro_members_is_active  ON pro_members (is_active);

-- 3) updated_at 자동 갱신 트리거
CREATE OR REPLACE FUNCTION update_pro_members_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pro_members_updated_at ON pro_members;
CREATE TRIGGER trg_pro_members_updated_at
    BEFORE UPDATE ON pro_members
    FOR EACH ROW EXECUTE FUNCTION update_pro_members_updated_at();

-- 4) RLS — 로그인 유저(admin)만 읽기/쓰기 허용
ALTER TABLE pro_members ENABLE ROW LEVEL SECURITY;

-- 기존 정책 제거 후 재생성
DROP POLICY IF EXISTS pro_members_select ON pro_members;
DROP POLICY IF EXISTS pro_members_insert ON pro_members;
DROP POLICY IF EXISTS pro_members_update ON pro_members;
DROP POLICY IF EXISTS pro_members_delete ON pro_members;

CREATE POLICY pro_members_select ON pro_members
    FOR SELECT TO authenticated USING (true);

CREATE POLICY pro_members_insert ON pro_members
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY pro_members_update ON pro_members
    FOR UPDATE TO authenticated USING (true);

CREATE POLICY pro_members_delete ON pro_members
    FOR DELETE TO authenticated USING (true);

-- 5) app_config에 pro_channel_id / pro_action_flag 초기값 추가
INSERT INTO app_config (key, value, description)
VALUES
    ('pro_channel_id',  '@batipro', '프로 채널 @username 또는 숫자 ID'),
    ('pro_action_flag', '{}',       '프로채널 액션 플래그 (초대/퇴장/연장)')
ON CONFLICT (key) DO NOTHING;

-- ============================================================
--  완료 확인
-- ============================================================
SELECT 'pro_members 테이블 생성 완료' AS result;
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'pro_members'
ORDER BY ordinal_position;
